version: '3.4'

services:
  internsadaptationservice.api:
    container_name: InternsAdaptationService.API
    image: internsadaptationservice.api
    build:
      context: .
      dockerfile: InternsAdaptationService.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development