version: '3.4'

services:
  internsadaptationservice.api:
    container_name: InternsAdaptationService.API
    image: internsadaptationservice.api
    build:
      context: .
      dockerfile: InternsAdaptationService.API/Dockerfile
    ports:
      - "5045:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  internsadaptationservice.db:
    container_name: InternsAdaptationService.db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7rVo}f)7JocU]2>ms)CztJYs=%v>WU2PF#gH2669*,K_kJ2m9Y
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes: 
  postgres-data: